quarkus.application.name=order-consumer-service

quarkus.http.port=8081

kafka.bootstrap.servers=kafka:9092

mp.messaging.incoming.orders.connector=smallrye-kafka
mp.messaging.incoming.orders.topic=orders
mp.messaging.incoming.orders.group.id=order-group
mp.messaging.incoming.orders.value.deserializer=org.ifglife.config.OrderDeserializer

mp.messaging.outgoing.processed.connector=smallrye-kafka
mp.messaging.outgoing.processed.topic=orders-processed
mp.messaging.outgoing.processed.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.dlq.connector=smallrye-kafka
mp.messaging.outgoing.dlq.topic=orders-dlq
mp.messaging.outgoing.dlq.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

quarkus.swagger-ui.always-include=true
