quarkus.application.name=order-producer-service

quarkus.http.port=8080

kafka.bootstrap.servers=kafka:9092

mp.messaging.outgoing.orders.connector=smallrye-kafka
mp.messaging.outgoing.orders.topic=orders
mp.messaging.outgoing.orders.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

quarkus.swagger-ui.always-include=true
